Add Katello 4.6 pipeline
theforeman/jenkins-jobs pull request #251
Opened 2022-08-04 16:07 UTC by sjha4

Adds 4.6 specific pipelines and vars. Haven't removed any older configs or pipelines but let me know if we should.

2022-08-04 19:53 UTC, ekohl requested changes
We recently made some changes and haven't reflected that in tool_belt. Could you also add the mapping to `theforeman.org/pipelines/test/foreman/vars.groovy`? This means PRs to foreman.git will check out the proper Katello version for the stable branch.

2022-08-04 20:38 UTC, sjha4 commented on theforeman.org/pipelines/test/foreman/vars.groovy
>      '3.3-stable': [
@ekohl..Thanks! Added 3.4 and 4.6 configs.

2022-08-05 13:11 UTC, ekohl requested changes

2022-08-05 13:11 UTC, ekohl commented on theforeman.org/pipelines/vars/katello/4.6.groovy
> +    'el7',
There won't be al EL7 release
```suggestion
```

2022-08-05 13:11 UTC, ekohl commented on theforeman.org/yaml/jobs/pipeline/katello-rpm-pipeline.yaml
> +      - '4.6'
Could you ensure a line ending at the end of the file?

2022-08-08 09:44 UTC, ekohl approved these changes
Thanks!

2022-08-08 09:45 UTC, merged