Remove Verify Version and Release from Pulp Packaging
theforeman/jenkins-jobs pull request #373
Opened 2023-11-06 19:58 UTC by Odilhao

We removed this from Pulpcore with #236 , now we have rpm/develop as well on pulpcore-packaging, addning another condition to verify the version only for foreman-packaging

2023-11-06 20:00 UTC, ekohl requested changes
Why is this check not needed on Pulp? It ensures you properly increase versions and that they are built correctly.

2023-11-06 20:14 UTC, Odilhao commented
In the past we had problem with cherrypicks that updated the version and carried one or two bumps, this would make this step of the pipeline fail.
And right now we have this PR theforeman/pulpcore-packaging#737 that is bumping `createrepo_c` and I'm not sure why it fails here, we already have the build done [here](http://koji.katello.org/koji/buildinfo?buildID=75904).

2023-11-06 20:36 UTC, ekohl commented
> In the past we had problem with cherrypicks that updated the version and carried one or two bumps, this would make this step of the pipeline fail.

But you you shouldn't do cherry picks for `rpm/develop`, so that's irrelevant.

> And right now we have this PR [theforeman/pulpcore-packaging#737](https://github.com/theforeman/pulpcore-packaging/pull/737) that is bumping `createrepo_c` and I'm not sure why it fails here, we already have the build done [here](http://koji.katello.org/koji/buildinfo?buildID=75904).

The reason is fails is that the spec creates two `python3-createrepo_c`:
```
[2023-11-06T19:31:35.790Z] + rpmspec -q --srpm --undefine=dist --undefine=foremandist '--queryformat=%{VERSION}' packages/createrepo_c/createrepo_c.spec
[2023-11-06T19:31:35.791Z] error: line 123: %package -n python3-createrepo_c: package python3-createrepo_c already exists
[2023-11-06T19:31:35.791Z] error: query of specfile packages/createrepo_c/createrepo_c.spec failed, can't parse
```

I can reproduce this on a minimal CentOS 8 Stream container:

```console
$ podman run -it --rm -v .:/packaging:Z centos:stream
# dnf install /usr/bin/rpmspec
# cd packaging/
# rpmspec -q --srpm --undefine=dist --undefine=foremandist '--queryformat=%{VERSION}' packages/createrepo_c/createrepo_c.spec
error: line 137: %package -n python3-createrepo_c: package python3-createrepo_c already exists
error: query of specfile packages/createrepo_c/createrepo_c.spec failed, can't parse
```

The reason is here:
```
# grep '%package -n' packages/createrepo_c/createrepo_c.spec
%package -n python%{python3_pkgversion}-%{name}
%package -n python3-%{name}
# rpm -E '%{python3_pkgversion}'
3
```

So both statements evaluate to the same package name. It doesn't know about modules to be enabled, so that's why it fails.

I think https://github.com/theforeman/pulpcore-packaging/pull/737#discussion_r1383952714 is a better solution that to disable the checks.

2023-11-07 16:14 UTC, ekohl commented
Given the checks phase now passes for https://github.com/theforeman/pulpcore-packaging/pull/737, can we close this?

2023-11-07 16:15 UTC, closed without merging

2023-11-07 16:15 UTC, Odilhao commented
Thanks for the help in the PR