Foreman 3.13 branching
theforeman/jenkins-jobs pull request #500
Opened 2024-11-05 16:59 UTC by pcreech

2024-11-05 18:29 UTC, ekohl requested changes

2024-11-05 18:29 UTC, ekohl commented on theforeman.org/yaml/jobs/test_3_13_stable.yaml
> +    name: test_3_12_stable
```suggestion
    name: test_3_13_stable
```

2024-11-06 16:20 UTC, pcreech commented on theforeman.org/yaml/jobs/test_3_13_stable.yaml
> +    name: test_3_12_stable
should be good now

2024-11-06 18:47 UTC, ekohl approved these changes

2024-11-06 18:47 UTC, merged